### ISSUE TITLE
Cobh Crash

### ISSUE THREAD

**Issue by Toxicshad0w** [Xcelled/mabicommerce#1]
I think this is an autodetect issue, not sure though. Basically, I installed Morrighan, ran everything fine, set MabiCommerce to connect to auto detect, ran that just fine, and then after opening the trade window in Port Cobh, MabiCommerce crashed. If it helps, MC was connected the entire time, and Morrighan didn't crash.

**Comment by Xcelled** [comment]
Have you ever traded in Cobh before? There's a current bug where if you have MabiCommerce open when visiting a post for the first time, you crash.

**Comment by Toxicshad0w** [comment]
Ohh I totally spaced that, even after reading the previous comment about Tailteann. That would explain it. Sorry then~

**Comment by Xcelled** [comment]
No problem. I'm going to be releasing the fix in a day or two. For now, doing a single starter run to gain some rating will fix it.
