### ISSUE TITLE
Mabicommerce Now a Hack

### ISSUE THREAD

**Issue by Surumon** [Xcelled/mabicommerce#12]
Latest patch by Nexon and NGS has now identified Mabicommerce as a hack.  Don't know if you can fix this, but there you have it.  A sad day, indeed.

**Comment by Xcelled** [comment]
Try renaming the executables.

**Comment by Surumon** [comment]
Same result.  I'll try renaming Morrighan as well.

**Comment by Surumon** [comment]
Tried renaming all executable files.  No dice, NGS still detects it and kicks you out.  For clarification, I was just running Mabicommerce and not Morrighan.  You get about a 2-3 minute grace period and then it kicks you off.

**Comment by Xcelled** [comment]
They also detect the neutered (aka harmless) version. As usual Nexon uses the blunt hammer of war...

![](http://i.imgur.com/olB0hX5.gif)

**Comment by Xcelled** [comment]
I have developed a workaround. I should have it posted in a day or two, but for now you can use the one I've attached here:

[MabiCommerce (2).zip](https://github.com/Xcelled/mabicommerce/files/285645/MabiCommerce.2.zip)

**Comment by michael5323** [comment]
This bug is still an issue not sure if I'm supposed to open a new report.
Anyways NGS is detecting MabiCommerce
