### ISSUE TITLE
PowerPatcher opens differently than MorriOneClick

### ISSUE THREAD

**Issue by Chaotix13567** [Xcelled/mabicommerce#16]
And doesn't work. Below are the two versions of Morrighan.log with each of the launch methods. PowerPatcher has Morrighan listening on a different port than MorriOneClick. NGS detects the MorriOneClick launch (which is able to pull the data to be used for MabiCommerce), but does not detect the PowerPatch launch (which gives either no data, or no useable data to MabiCommerce). I looked around for a way to change this, but could not find anywhere to change it. Not sure if this is the correct place to put this, but it is out there now.

(These are what the Morrighan.log file recorded after using each of the launch methods)
MorriOneClick Log
4/17/2017 11:59:10 PM [Info] - Morrighan 1.0.5862.36118
4/17/2017 11:59:10 PM [Info] - Starting server...
4/17/2017 11:59:10 PM [Info] - Server listening on '127.0.0.1:63085'
4/17/2017 11:59:10 PM [Info] - Starting Alissa communicator...
4/17/2017 11:59:10 PM [Info] - Starting client...
4/17/2017 11:59:12 PM [Info] - Started client: Client.exe code:1622 ver:249 chatip:208.85.109.37 chatport:8002 setting:"file://data/features.xml=Regular, USA" logip:127.0.0.1 logport:63085
4/17/2017 11:59:12 PM [Info] - Morrighan is ready to serve you

PowerPatcher Log
4/18/2017 12:00:20 AM [Info] - Morrighan 1.0.5862.36118
4/18/2017 12:00:20 AM [Info] - Starting server...
4/18/2017 12:00:20 AM [Info] - Server listening on '127.0.0.1:63103'
4/18/2017 12:00:20 AM [Info] - Starting Alissa communicator...
4/18/2017 12:00:20 AM [Info] - Starting client...
4/18/2017 12:00:20 AM [Info] - Started client: Client.exe code:1622 ver:249 chatip:208.85.109.37 chatport:8002 setting:"file://data/features.xml=Regular, USA" logip:127.0.0.1 logport:63103
4/18/2017 12:00:20 AM [Info] - Morrighan is ready to serve you

The NGS detection is a separate issue, and is used here as additional proof that there is a difference in launch methods.

**Comment by Xcelled** [comment]
The port Morrighan listens on isn't fixed. It changes every run. All that's important is that the client is directed to that same port, which it is.

Both PowerPatcher and MorriOneClick do the same things: read the client start arguments from Nexon and then hand those off to Morrighan,

I don't see anything obviously wrong with the arguments being passed to Morrighan. If you've checked all the easy stuff (run as admin, etc), I'd advise you to open an issue on [Morrighan](https://github.com/exectails/Morrighan). (You can link to this issue).

NGS detection is in #13.

Side note: my understanding is Nexon completely changed their patch process so PowerPatcher won't work any more.

**Comment by Chaotix13567** [comment]
The issue appears to have been fixed by an update to Morrighan.
