### ISSUE TITLE
Not Valid win32 aplication error

### ISSUE THREAD

**Issue by g6qwerty** [Xcelled/mabicommerce#3]
Is this a 64bit only application? its not running on fully updated win XP 32bit. even though mabi runs fine.

**Comment by Xcelled** [comment]
MabiCommerce requires [.Net framework version 4.5](http://www.microsoft.com/en-us/download/details.aspx?id=30653). Microsoft dropped .Net's compatibility with Windows XP starting with version 4.5.

In short: MabiCommerce requires Vista or higher, Changing that would probably require code refactoring, something that's not likely to happen. (Side note: You really shouldn't be running XP anymore...)

**Comment by Xcelled** [comment]
Side note: Mabi's [system requirements](http://mabinogi.nexon.net/Support/ClientDrivers) say that Win 7 or newer is required for the game.

**Comment by g6qwerty** [comment]
Oh Mabi use to say only windows xp and up, didn't know it had changed, because mabi is still running and not complaining.
