### ISSUE TITLE
MabiCommerce.exe has stopped working

### ISSUE THREAD

**Issue by Shiva666** [Xcelled/mabicommerce#5]
After following all instructions given to use this mod with auto-detect for non-power patch users, the morrioneclick starts up the game with the "M" on the upper left corner of the screen. I log in, stand in front of Trade post and keep mabi in windowed mode and double click open the MabiCommerce.exe it says "it has stopped working" i tried it running as and admin, changing compatibility too..it doesn't start. I am using 32-bit Windows 7, 4GB RAM, 2.70GHz processor....this is the exact error log i get : 

Problem signature:
  Problem Event Name:   CLR20r3
  Problem Signature 01: mabicommerce.exe
  Problem Signature 02: 2.0.2.0
  Problem Signature 03: 5539da1e
  Problem Signature 04: mscorlib
  Problem Signature 05: 4.0.0.0
  Problem Signature 06: 4ba1da6f
  Problem Signature 07: 196e
  Problem Signature 08: 16
  Problem Signature 09: System.AggregateException
  OS Version:   6.1.7601.2.1.0.256.1
  Locale ID:    16393
  Additional Information 1: 0a9e
  Additional Information 2: 0a9e372d3b4ad19135b953a78882e789
  Additional Information 3: 0a9e
  Additional Information 4: 0a9e372d3b4ad19135b953a78882e789

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

..........................the screenshot of the error is this : 

![123456](https://cloud.githubusercontent.com/assets/14540395/9986787/5c9b5d96-605e-11e5-975a-79fe5bf18c4f.jpg)

**Comment by Xcelled** [comment]
That error is usually caused by lack of a "data" folder, a corrupted program, or a missing file on your system. Try deleting MabiCommerce, redownloading it, and starting again. If that doesn't work, try installing this: http://www.microsoft.com/en-us/download/details.aspx?id=40784

**Comment by Shiva666** [comment]
i did exactly wat u said @Xcelled  but still am getting the same error ...

**Comment by Xcelled** [comment]
I have just released a new version of MabiCommerce designed to give additional information if something goes wrong. Please try that one.

**Comment by Xcelled** [comment]
If any new information comes to light, please reopen the issue.
