### ISSUE TITLE
Can't check off any of the options.

### ISSUE THREAD

**Issue by Cronundrum** [Xcelled/mabicommerce#7]
The options, Like having an alpaca robe. I'm thinking it might be because my Windows Theme.
When I click on the checkbox nothing happens.

![vgyhkujli](https://cloud.githubusercontent.com/assets/15079244/10418944/2c55a424-701d-11e5-93a8-97ba383e16b2.png)

**Comment by Xcelled** [comment]
- Have you tried clicking on both the box and the text?
- Do other checkboxes in the program work? (For example, in the settings window)
- If you change your theme, do they start working?
- Does this happen with other checkboxes in other programs?

**Comment by Xcelled** [comment]
I'm going to close this as not a bug, since no one else has reported it, and it doesn't seem tied to MabiCommerce. Please reopen it if you have more information.
